stages:
  - build
  - test
  - deploy

singularity:
  stage: build
  needs: []  # run immediately
  tags:
    - docker
  image:
    name: quay.io/singularity/singularity:v3.2.1
    entrypoint: [""]
  script:
    - cp -r . /tmp/ink-id
    - singularity build inkid.sif singularity/inkid.def
  artifacts:
    paths:
      - inkid.sif
    expire_in: 1 day
  rules:
    # prevent builds just because branch is tagged
    - if: $CI_COMMIT_TAG
      when: never
    # don't run on the gitlab.com mirror
    - if: '$CI_PROJECT_URL =~ /.*gitlab\.com.*/'
      when: never
    # only build on develop or when you manually start a job with the BUILD_NIGHTLY env var set to true
    - if: '$CI_COMMIT_BRANCH == "develop" || $BUILD_NIGHTLY == "true"'

# Build wheels for Linux
.build/manylinux:
  stage: build
  needs: []
  tags:
    - docker
  image: quay.io/pypa/manylinux2014_x86_64
  script:
    - bash build/build-wheels.sh
  variables:
    PLAT: "manylinux2014_x86_64"
  artifacts:
    paths:
      - wheelhouse

# Various Linux flavours on Python 3.8.
build/manylinux/3.8:
  extends: .build/manylinux
  variables:
    PYBIN: /opt/python/cp38-cp38/bin

# Various Linux flavours on Python 3.9.
build/manylinux/3.9:
  extends: .build/manylinux
  variables:
    PYBIN: /opt/python/cp39-cp39/bin

.test:
  stage: test
  needs: []
  before_script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install --upgrade pip
    - pip install -e .
  script:
    - inkid-train-and-predict -h
    - python -m unittest
  tags:
    - docker

test:3.8:
  extends: .test
  image: python:3.8

test:3.9:
  extends: .test
  image: python:3.9

#deploy:pypi:
#  stage: deploy
#  rules:
#    - if: '$CI_COMMIT_TAG =~ /^v.*$/'
#  image: python:3.9
#  before_script:
#    - python -m pip install --upgrade pip build setuptools wheel twine
#  script:
#    - python -m build
#    - python -m twine upload dist/*
